final int SCROLLHEIGHT = 1080;
final int SCROLLWIDTH = 40;
final int SCREEN_X = 1800;
final int SCREEN_Y = 1000;
int barHeightH=5;  //horizontal
int barWidthH=350;
int barHeightV=-300;    //vertical
int barWidthV=5;
int barX=100;  //useful,funny,cool bars
int barY=900;
int barGraphWidth=85;
int oneRating=-1*(barHeightV/5);
int TEST=0;
int starBoxX= 1500;
int starBoxW=150;
int starBoxH=50;
int starBoxY=900;
final int REVIEW_X_POS = 900;
final int TEXT_X = 20;
final int TEXT_Y = 30;
final int EVENT_BUTTON1=1;
final int EVENT_BUTTON2=2;
final int EVENT_NULL=0;
final int WIJ_Y = 500;