final int SCROLLHEIGHT = 1080;
final int SCROLLWIDTH = 40;
final int SCREEN_X = 1800;
final int SCREEN_Y = 1000;
int barHeightH=5;  //horizontal
int barWidthH=350;
int barHeightV=-300;    //vertical
int barWidthV=5;
int barX=100;  //useful,funny,cool bars
int barY=900;
int barGraphWidth=85;
int oneRating=-1*(barHeightV/5);
int TEST=0;
int starBoxX= 200;
int starBoxW=150;
int starBoxH=50;
int starBoxY=200;
final int REVIEW_X_POS = 800;
final int LIST_X_POS = 800;
final int LEFT_X_POS = 400;
final int RIGHT_X_POS = 1200;
final int TEXT_X = 20;
final int TEXT_Y = 30;
final int EVENT_BUTTON1=1;
final int EVENT_BUTTON2=2;
final int EVENT_BUTTON3=3;
final int EVENT_BUTTON4=4;
final int EVENT_BUTTON5=5;
final int EVENT_BUTTON6 = 6; // home page users button 
final int EVENT_BUTTON7 = 7; // home page businesses button
final int EVENT_BUTTON8 =8; // home page most recent reviews
final int EVENT_BUTTON9 = 9; // home page top rated reviews
final int EVENT_BUTTON10=10;
final int EVENT_BUTTON11=11;
final int EVENT_BUTTON12=12;
final int EVENT_BUTTON13=13;
final int EVENT_BUTTON14=14;
final int EVENT_BUTTON15=15;
final int EVENT_BUTTON16=16;
final int EVENT_BUTTON17=17;
final int EVENT_BUTTON18=18;
final int EVENT_BUTTON19=19;
final int EVENT_BUTTON20=20;
final int EVENT_BUTTON21=21;
final int EVENT_BUTTON22=22;
final int EVENT_BUTTON23=23;
final int EVENT_BUTTON24=24;
final int EVENT_BUTTON25=25;
final int EVENT_BUTTON26 =26;
final int EVENT_BUTTON27 = 27;
final int EVENT_BUTTON28 = 28;
final int EVENT_BUTTON29 = 29;
final int REVIEW_SCREEN_INT = 1;
final int BUSINESS_SCREEN_INT = 2;
final int USER_SCREEN_INT = 3;
final int HOME_SCREEN_INT = 4;
final int TOP_RATED_SCREEN_INT=6;
final int RECENT_SCREEN_INT=5;
final int EVENT_NULL=0;
final int WIJ_Y = 500;
final int WIJ_WIDTH = 100;
final int WIJ_HEIGHT= 40;
final int WIJ_X = 300;
final int NEW_WIJ_X = 300;
final int NEW_WIJ_Y = 100;
final int REVIEW_SCREEN = 1;
final int BIZ_SCREEN = 2;
final int USER_SCREEN =3;
final int USERNAME_WIJ_WIDTH = 100;
final int USERNAME_WIJ_HEIGHT = 40;